# Generated by Django 4.1.7 on 2023-03-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], default=1, verbose_name='Тип')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='network.contacts', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Распространитель',
                'verbose_name_plural': 'Распространители',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.BigIntegerField(default=0, verbose_name='Задолженность перед поставщиком')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_distributor', to='network.distributor', verbose_name='Распространитель продукции')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='link_supplier', to='network.distributor', verbose_name='Поставщик продукции')),
            ],
            options={
                'verbose_name': 'Звено сети продаж',
                'verbose_name_plural': 'Звенья сети продаж',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('release', models.DateTimeField(null=True, verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('distributor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_distr_1', to='network.link', verbose_name='Распространитель №1')),
                ('distributor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_distr_2', to='network.link', verbose_name='Распространитель №2')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.link', verbose_name='Производитель продукции')),
            ],
            options={
                'verbose_name': 'Сеть продаж',
                'verbose_name_plural': 'Сеть продаж',
            },
        ),
        migrations.AddField(
            model_name='distributor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='network.product', verbose_name='Продукт'),
        ),
    ]
