# Generated by Django 4.1.7 on 2023-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['pk'], 'verbose_name': 'Звено сети продаж', 'verbose_name_plural': 'Звенья сети продаж'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Сеть продаж', 'verbose_name_plural': 'Сети продаж'},
        ),
        migrations.AlterField(
            model_name='link',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
